name: imas_composer


channels:
  - conda-forge
  - ga-fdp

dependencies:
  - python==3.13
  - awkward
  - pyyaml
  - pytest
  - numpy 2.*
  - mdsplus
  - matplotlib
  - cython
  - uncertainties
  - pint
  - netcdf4
  - boto3
  - botocore
  - pymongo
  - dnspython
  - xmltodict
  - xarray
  - pyro5
  - scipy
  - h5py
  - conda-build
  - pytest-benchmark
  - pip
  - pip:
    # Install imas_composer in editable mode from current directory
    - -e .